title: Joe Eckstein
description: Entertainment Automation Professional
logo: /assets/img/logo.svg
google_analytics: 
show_downloads: false
theme: jekyll-theme-minimal
timezone: America/New_York


gems:
  - jekyll-mentions
