title: Joe Eckstein
description: Entertainment Automation Professional
logo: /assets/img/logo.svg
google_analytics: UA-71710819-1
show_downloads: false
show_sidenav: true
show_linkbar: true
theme: jekyll-theme-minimal
url: "https://www.jeckstei.com"

gems:
  - jekyll-mentions

plugins:
  - jekyll-sitemap