title: Joe Eckstein
description: Entertainment Automation Professional
logo: /assets/img/logo.svg
google_analytics: UA-71710819-1
show_downloads: false
show_sidenav: true
show_linkbar: true
theme: jekyll-theme-minimal
url: "https://www.jeckstei.com"
author: Joe Eckstein
paginate: 2
paginate_path: "/blog/page:num/"

collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title

plugins:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-paginate

